<?php

define("TITLE","Создание резервной копии базы данных");
define("SELECT_ACTIONS","Выберите действия");
define("CREATE_BACKUP","Создать резервную копию базы данных");
define("DOWNLOAD_PACKED_BACKUP","Загрузить упакованные резервные копии");
define("REMOVE_BACKUP_DIRECTORY","Удалить директории с резервными копиями");
define("CONFIRM_REMOVE_DIRECTORY","Вы действительно хотите удалить директории с резервными копиями?");
define("MSG_REQUEST_IS_READY","Запрос для создания таблиц готов, он находится в файле");
define("DIRECTORY_BACKUP","Директория резервных копий");
define("TO_DOWNLOAD_CLICK_LINK","Чтобы скачать нажмите на ссылку");
define("DATECREATION_BACKUP","Дата создания резервных копий");
define("REMOVE_DIR_MSG","Директория %DIR% удалена.<br>");
define("GZIP_PACK_MSG","Файл %FILENAME% упакован.<br>");

?>