<?php

define("TITLE","Смена пароля");
define("MSG_ENTER_CURRENT_PASSWD","Введите текущий пароль!");
define("MSG_PASSWORD_ISNT_ENTERED","Пароль не введен!");
define("MSG_REENTER_PASSWORD","Введите повторно пароль!");
define("MSG_PASSWORDS_DONT_MATCH","Пароли не совпадают!");
define("MSG_CURRENT_PASSWD_INCORRECT","Неверно введен текущий пароль!");
define("PASSWD_CHANGED","Пароль сменен");
define("ENTER_NEW_PASSWORD","Введите новый пароль");
define("TABLECOLMN_CURRENT_PASSWD","Текущий пароль");
define("TABLECOLMN_PASSWD","Пароль");
define("TABLECOLMN_AGAIN_PASSWD","Повтор пароля");
define("SAVE","сменить");
define("IDENTIFIED_FOLLOWING_ERRORS","Выявлены следующие ошибки");

?>