<?php

define("TITLE","Экспорт адресов электронной почты");
define("TABLECOLMN_EXTENSION","Расширение");
define("TABLECOLMN_COMPRESSION","Сжатие");
define("TABLECOLMN_COMPRESSION_OPTION_1",'Нет&nbsp;&nbsp;&nbsp;');
define("TABLECOLMN_COMPRESSION_OPTION_2",'Архивировать в zip&nbsp;&nbsp;&nbsp;');
define("TABLECOLMN_FIELDS","Поля");
define("MSG_ENTER_FILE_EXTENSION","Укажите расширение файла!");

?>