<?php

define("TITLE","Установка");
define("TITLE_NAME","Почтовая рассылка");
define("TITLE_NAME_2","Программа установки");
define("DBLOCATION","Адрес сервера базы данных MySQL");
define("DBLOGIN","Логин базы данных");
define("DBPASSWD","Пароль базы данных");
define("DBNAME","Имя базы данных");
define("PREFIX","Префикс");
define("DBCHARSET","Кодировка");
define("FORM_LANGUAGE","Язык");
define("FORM_LANGUAGE_RU","Русский");
define("FORM_LANGUAGE_EN","English");
define("MSG_UNABLE_CONNECT_TO_DB","Невозможно установить соединение с сервером базы данных! Проверьте правильность ввода адреса сервера, имени и пароля пользователя.");
define("MSG_CONNECTION_ESTABLISHED","Соединение с сервером установлено.");
define("MSG_DB_CREATED","Создаем таблицы...");
define("COULDNT_GET_ACCESS_TO_DB","Не удалось получить доступ к базе данных");
define("MSG_GET_ACCESS_TO_DB","Получен доступ к базе данных");
define("MSG_FAILED_TO_CREATE_TABLES","Не удалось создать таблицы в базе данных");
define("MSG_THEY_ALREADY_EXIST","Возможно они уже существуют.");
define("MSG_TABLE_SUCCESSFULLY_CREATED","Таблицы успешно созаны в базе данных");
define("MSG_ERROR_INSTALLATION_CANNOT_WRITE","Ошибка инсталяции! Не могу произвести запись в файл connect.inc!");
define("MSG_ERROR_INSTALLATION_CANNOT_WRITE_2","Ошибка при инсталляции! Попробуйте установить заново или проверьте права доступа (CHMOD) для файла connect.inc");
define("MSG_INSTALLATION_IS_COMPLETE","Создан конфигурационный файл системы администрирования.");
define("MSG_INSTALLATION_IS_COMPLETE_2","Инсталляция завершена. Не забудьте удалить установочный файл install.php!");
define("MSG_ERROR_INSTALLATION_FILE_ISNT_WRITABLE","Ошибка инсталяции! Файл connect.inc недоступен для записи.");
define("MSG_ERROR_INSTALLATION_FILE_ISNT_WRITABLE_2","Инсталляция не завершена. Не удалось создать файл кофигурации connect.inc. Возможно файл не сушествует или неправельно установлены права доступа (CHMOD)");
define("MSG_ALERT","Пожалуйсто заполните поле");
define("FORM_CREATE","Создать");

?>