<?php

define("TITLE","Управление подписчиками");
define("ALERTSELECTACTION","Выберите действие!");
define("ALERTCONFIRMREMOVE","Вы действительно хотите удалить?");
define("FORMSEARCH_NAME","E-mail или имя");
define("NUMBER_OF_SUBSCRIBERS","Количество подписчиков");
define("MSG_NOTFOUND","По вашему запросу ничего не найдено!");
define("TABLECOLMN_CHECK_ALLBOX","Отметить все/Снять отметку у всех");
define("TABLECOLMN_CHECKBOX","Отметить/Снять отметку");
define("TABLECOLMN_NAME","Имя");
define("TABLECOLMN_EMAIL","E-mail");
define("TABLECOLMN_CATEGORY","Категория");
define("TABLECOLMN_STATUS","Статус");
define("TABLECOLMN_ADDED","Добавлен");
define("STATUS_ACTIVE","Активен");
define("STATUS_NOACTIVE","Неактивен");
define("EDITUSER","Редактировать данные подписчика");

?>