<?php

define("TITLE","Редактирование рассылки");
define("MSG_SUBJECT_EMPTY","Отсутствует заголовок!");
define("MSG_TEXT_EMPTY","Содержание письма не введено!");
define("MSG_ADD_MAILING","Рассылка добавлена.");
define("FORM_SUBJECT","Тема");
define("FORM_CONTENTS","Содержание");
define("FORM_NOTE",'<b>Поддерживаемые теги:</b> %NAME% - имя подписчика, %DAYS% - количество дней на активацию подписки, <br>%UNSUB% - ссылка для удаления рассылки,<br>
%SERVER_NAME% - адрес сайта');
define("FORM_ATTACH","Присоединить файл");
define("FORM_ATTACHMENTS","Вложения");
define("FORM_DEL_ATTACHMENTS","Удалить вложения");
define("FORM_CATEGORY_SUBSCRIBERS","Присоединить файл");
define("FORM_SENT_TO_ALL","Разослать всем");
define("FORM_PRIORITY"," Важность");
define("FORM_PRIORITY_HIGH","Высокая");
define("FORM_PRIORITY_LOW","Низкая");
define("FORM_PRIORITY_NORMAL","Нормальная");

?>