<?php

define("TITLE","Главная страница");
define("TABLECOLMN_CHECK_ALLBOX","Отметить все/Снять отметку у всех");
define("TABLECOLMN_MAILER","Рассылка");
define("TABLECOLMN_DATE_CREATION","Дата добавления");
define("TABLECOLMN_CATEGORY","Категория");
define("TABLECOLMN_POSITION","Позиция");
define("TABLECOLMN_ACTIVITY","Активность");
define("TABLECOLMN_EDIT","Редактировать");
define("TABLECOLMN_SEND","Разослать");
define("TABLECOLMN_CHECKBOX","Отметить/Снять отметку");
define("TABLECOLMN_UP","Вверх на одну позицию");
define("TABLECOLMN_DOWN","Вниз на одну позицию");
define("TABLECOLMN_EDIT_MAILINGTEXT","Редактировать рассылку");
define("TABLECOLMN_SEND_MAIL","Разослать рассылку подписчикам");
define("ALERTSEND","Только активные рассылки можно рассылать!");
define("ALERTSELECTACTION","Выберите действие!");
define("ALERTCONFIRMREMOVE","Вы действительно хотите удалить?");
define("ALERTERRORINTERFACE","Ошибка инициализации интерфейса!");
define("ALERTERRORSERVER","При обращении к серверу возникли проблемы:");
define("COUNTSENT","Отправлено:");

?>