<?php

define("TITLE","Backing up the database");
define("SELECT_ACTIONS","Select actions");
define("CREATE_BACKUP","Create a backup copy of the database");
define("DOWNLOAD_PACKED_BACKUP","Download the packed backup copies");
define("REMOVE_BACKUP_DIRECTORY","Remove the directories with backup copies");
define("CONFIRM_REMOVE_DIRECTORY","Are you sure you want to remove a directory with backup copies?");
define("MSG_REQUEST_IS_READY","A request to create a table is ready and it is in the file");
define("DIRECTORY_BACKUP","Directory of backup copies");
define("TO_DOWNLOAD_CLICK_LINK","To download it click on the link");
define("DATECREATION_BACKUP","Making date of backup copies");
define("REMOVE_DIR_MSG","Directory %DIR% has been removed.<br>");
define("GZIP_PACK_MSG","the file %FILENAME% has been packed successfully.<br>");

?>