<?php

define("TITLE","Changing the password");
define("MSG_ENTER_CURRENT_PASSWD","Please enter the current password!");
define("MSG_PASSWORD_ISNT_ENTERED","The password was not entered!");
define("MSG_REENTER_PASSWORD","Please re-enter new password!");
define("MSG_PASSWORDS_DONT_MATCH","Passwords do not match!");
define("MSG_CURRENT_PASSWD_INCORRECT","Сurrent password is incorrect!");
define("PASSWD_CHANGED","Password has been changed.");
define("ENTER_NEW_PASSWORD","Please enter a new password");
define("TABLECOLMN_CURRENT_PASSWD","Current password");
define("TABLECOLMN_PASSWD","Password");
define("TABLECOLMN_AGAIN_PASSWD","Repeat password");
define("SAVE","change");
define("IDENTIFIED_FOLLOWING_ERRORS","While changing the password the following errors occurred");

?>