<?php

define("TITLE","Editing the mailing");
define("MSG_SUBJECT_EMPTY","Subject is empty!");
define("MSG_TEXT_EMPTY","Contents of mailing is empty!");
define("MSG_CHANGE","Mailing list has been change.");
define("FORM_SUBJECT","Subject");
define("FORM_CONTENTS","Contents");
define("FORM_NOTE",'<b>Supported tags:</b> %NAME% - Username, %DAYS% - number of days on subscription activation, <br>%CONFIRM% - link to confirm email addresses, %UNSUB% - unsubscribt link<br>
%SERVER_NAME% - website address');
define("FORM_ATTACH","Attach a file");
define("FORM_ATTACHMENTS","Attachments");
define("FORM_DEL_ATTACHMENTS","Remove attachments");
define("FORM_CATEGORY_SUBSCRIBERS","Category subscribers");
define("FORM_SENT_TO_ALL","Sent to all");
define("FORM_PRIORITY","Priority");
define("FORM_PRIORITY_HIGH","high");
define("FORM_PRIORITY_LOW","low");
define("FORM_PRIORITY_NORMAL","normal");

?>