<?php

define("TITLE","Home");
define("TABLECOLMN_CHECK_ALLBOX","Check all/Uncheck all");
define("TABLECOLMN_MAILER","Mailer");
define("TABLECOLMN_DATE_CREATION","Creation date");
define("TABLECOLMN_CATEGORY","Category");
define("TABLECOLMN_POSITION","Position");
define("TABLECOLMN_ACTIVITY","Activity");
define("TABLECOLMN_EDIT","Edit");
define("TABLECOLMN_SEND","Send");
define("TABLECOLMN_CHECKBOX","Check/Uncheck");
define("TABLECOLMN_UP","Up");
define("TABLECOLMN_DOWN","Down");
define("TABLECOLMN_EDIT_MAILINGTEXT","Edit mailing text");
define("TABLECOLMN_SEND_MAIL","Send the mail to subscribers");
define("ALERTSEND","Only active mails, you can send!!");
define("ALERTSELECTACTION","Choose an action!");
define("ALERTCONFIRMREMOVE","Are you sure you want to remove?");
define("ALERTERRORINTERFACE","Error initializing the interface!");
define("ALERTERRORSERVER","Error while connect to server:");
define("COUNTSENT","Sent:");

?>