<?php

define("TITLE","Installation");
define("TITLE_NAME","PHP Newsletter");
define("TITLE_NAME_2","The installation program");
define("DBLOCATION","Address of the MySQL database server");
define("DBLOGIN","Database login");
define("DBPASSWD","Database password");
define("DBNAME","Database name");
define("PREFIX","Prefix");
define("DBCHARSET","Database charset");
define("FORM_LANGUAGE","Language");
define("FORM_LANGUAGE_RU","Русский");
define("FORM_LANGUAGE_EN","English");
define("MSG_UNABLE_CONNECT_TO_DB","Cannot connect to Database Server! Please check your server address, login and password");
define("MSG_CONNECTION_ESTABLISHED","Connection to the server has been established.");
define("MSG_DB_CREATED","Creating tables...");
define("COULDNT_GET_ACCESS_TO_DB","Failed to get access to the database");
define("MSG_GET_ACCESS_TO_DB","The database access.");
define("MSG_FAILED_TO_CREATE_TABLES","Failed to create table in the Database");
define("MSG_THEY_ALREADY_EXIST","Perhaps they already exist.");
define("MSG_TABLE_SUCCESSFULLY_CREATED","Tables has been created successfully in Database");
define("MSG_ERROR_INSTALLATION_CANNOT_WRITE","Installation error! Cannot write to the file connect.inc!");
define("MSG_ERROR_INSTALLATION_CANNOT_WRITE_2","Installation error! Please try again installing it or check the permissions (CHMOD) of connect.inc");
define("MSG_INSTALLATION_IS_COMPLETE","Configuration file has been created successfully.");
define("MSG_INSTALLATION_IS_COMPLETE_2","Installation is complete! Please don't forget to delete the installation file install.php");
define("MSG_ERROR_INSTALLATION_FILE_ISNT_WRITABLE","Installation error! File connect.inc is not writable.");
define("MSG_ERROR_INSTALLATION_FILE_ISNT_WRITABLE_2","nstallation is not complete. Could not create the configuration file connect.inc. Perhaps the file is not exist or its permissions (CHMOD) is set uncorrectly.");
define("MSG_ALERT","Please fill in");
define("FORM_CREATE","create");

?>