<?php

define("TITLE","Management of subscribers");
define("ALERTSELECTACTION","Choose your action!");
define("ALERTCONFIRMREMOVE","Are you sure you want to delete the selected users?");
define("FORMSEARCH_NAME","E-mail or username");
define("NUMBER_OF_SUBSCRIBERS","Number of Subscribers");
define("MSG_NOTFOUND","Sorry, not found!");
define("TABLECOLMN_CHECK_ALLBOX","Check all/Uncheck all");
define("TABLECOLMN_CHECKBOX","Check/Uncheck");
define("TABLECOLMN_NAME","Name");
define("TABLECOLMN_EMAIL","E-mail");
define("TABLECOLMN_CATEGORY","Category");
define("TABLECOLMN_STATUS","Status");
define("TABLECOLMN_ADDED","Added");
define("STATUS_ACTIVE","active");
define("STATUS_NOACTIVE","inactive");
define("EDITUSER","Edit user");

?>